'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace EVASoap
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", ConfigurationName:="EVASoap.pacs_soap_service")>  _
    Public Interface pacs_soap_service
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación authenticate no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="authenticate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function authenticate(ByVal request As EVASoap.authenticate1) As EVASoap.authenticateResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="authenticate", ReplyAction:="*")>  _
        Function authenticateAsync(ByVal request As EVASoap.authenticate1) As System.Threading.Tasks.Task(Of EVASoap.authenticateResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación SendOrder no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="SendOrder", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SendOrder(ByVal request As EVASoap.SendOrder1) As EVASoap.send_orderResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="SendOrder", ReplyAction:="*")>  _
        Function SendOrderAsync(ByVal request As EVASoap.SendOrder1) As System.Threading.Tasks.Task(Of EVASoap.send_orderResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación GetOrder no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="GetOrder", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetOrder(ByVal request As EVASoap.GetOrder1) As EVASoap.OrderResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="GetOrder", ReplyAction:="*")>  _
        Function GetOrderAsync(ByVal request As EVASoap.GetOrder1) As System.Threading.Tasks.Task(Of EVASoap.OrderResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación CancelOrder no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="CancelOrder", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CancelOrder(ByVal request As EVASoap.CancelOrder1) As EVASoap.CancelOrderResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="CancelOrder", ReplyAction:="*")>  _
        Function CancelOrderAsync(ByVal request As EVASoap.CancelOrder1) As System.Threading.Tasks.Task(Of EVASoap.CancelOrderResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación ScheduleOrder no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="ScheduleOrder", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function ScheduleOrder(ByVal request As EVASoap.ScheduleOrder1) As EVASoap.schedule_orderResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="ScheduleOrder", ReplyAction:="*")>  _
        Function ScheduleOrderAsync(ByVal request As EVASoap.ScheduleOrder1) As System.Threading.Tasks.Task(Of EVASoap.schedule_orderResponse1)
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que la operación CancelAppointment no es RPC ni está encapsulada en un documento.
        <System.ServiceModel.OperationContractAttribute(Action:="CancelAppointment", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CancelAppointment(ByVal request As EVASoap.CancelAppointment1) As EVASoap.cancel_appointmentResponse1
        
        <System.ServiceModel.OperationContractAttribute(Action:="CancelAppointment", ReplyAction:="*")>  _
        Function CancelAppointmentAsync(ByVal request As EVASoap.CancelAppointment1) As System.Threading.Tasks.Task(Of EVASoap.cancel_appointmentResponse1)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class RequestHeader
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private emailField As String
        
        Private passwordField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
                Me.RaisePropertyChanged("email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
                Me.RaisePropertyChanged("password")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class cancel_appointmentResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private cancel_appointmentResultField As SendOrderResponseComplex
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property cancel_appointmentResult() As SendOrderResponseComplex
            Get
                Return Me.cancel_appointmentResultField
            End Get
            Set
                Me.cancel_appointmentResultField = value
                Me.RaisePropertyChanged("cancel_appointmentResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class SendOrderResponseComplex
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private orderField As OrderResponseComplex
        
        Private patientField As PatientResponseComplex
        
        Private appointmentField As AppointmentResponseComplex
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Order() As OrderResponseComplex
            Get
                Return Me.orderField
            End Get
            Set
                Me.orderField = value
                Me.RaisePropertyChanged("Order")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Patient() As PatientResponseComplex
            Get
                Return Me.patientField
            End Get
            Set
                Me.patientField = value
                Me.RaisePropertyChanged("Patient")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property Appointment() As AppointmentResponseComplex
            Get
                Return Me.appointmentField
            End Get
            Set
                Me.appointmentField = value
                Me.RaisePropertyChanged("Appointment")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class OrderResponseComplex
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As String
        
        Private statusField As String
        
        Private folioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
                Me.RaisePropertyChanged("Status")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Folio() As String
            Get
                Return Me.folioField
            End Get
            Set
                Me.folioField = value
                Me.RaisePropertyChanged("Folio")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class PatientResponseComplex
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As String
        
        Private identifierField As String
        
        Private nameField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Identifier() As String
            Get
                Return Me.identifierField
            End Get
            Set
                Me.identifierField = value
                Me.RaisePropertyChanged("Identifier")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class AppointmentResponseComplex
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private idField As String
        
        Private nameField As String
        
        Private roomIdentifierField As String
        
        Private startDateField As Date
        
        Private endDateField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Id() As String
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
                Me.RaisePropertyChanged("Id")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property RoomIdentifier() As String
            Get
                Return Me.roomIdentifierField
            End Get
            Set
                Me.roomIdentifierField = value
                Me.RaisePropertyChanged("RoomIdentifier")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property StartDate() As Date
            Get
                Return Me.startDateField
            End Get
            Set
                Me.startDateField = value
                Me.RaisePropertyChanged("StartDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property EndDate() As Date
            Get
                Return Me.endDateField
            End Get
            Set
                Me.endDateField = value
                Me.RaisePropertyChanged("EndDate")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class CancelAppointment
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private orderIdField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property OrderId() As String
            Get
                Return Me.orderIdField
            End Get
            Set
                Me.orderIdField = value
                Me.RaisePropertyChanged("OrderId")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class schedule_orderResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private schedule_orderResultField As SendOrderResponseComplex
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property schedule_orderResult() As SendOrderResponseComplex
            Get
                Return Me.schedule_orderResultField
            End Get
            Set
                Me.schedule_orderResultField = value
                Me.RaisePropertyChanged("schedule_orderResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class ScheduleOrder
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private orderIdField As String
        
        Private appointmentDateField As Date
        
        Private appointmentDurationField As Byte
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property OrderId() As String
            Get
                Return Me.orderIdField
            End Get
            Set
                Me.orderIdField = value
                Me.RaisePropertyChanged("OrderId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property AppointmentDate() As Date
            Get
                Return Me.appointmentDateField
            End Get
            Set
                Me.appointmentDateField = value
                Me.RaisePropertyChanged("AppointmentDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property AppointmentDuration() As Byte
            Get
                Return Me.appointmentDurationField
            End Get
            Set
                Me.appointmentDurationField = value
                Me.RaisePropertyChanged("AppointmentDuration")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class CancelOrderResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private cancel_orderResultField As SendOrderResponseComplex
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property cancel_orderResult() As SendOrderResponseComplex
            Get
                Return Me.cancel_orderResultField
            End Get
            Set
                Me.cancel_orderResultField = value
                Me.RaisePropertyChanged("cancel_orderResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class CancelOrder
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private orderIdField As String
        
        Private cancelReasonField As String
        
        Private cancelDescriptionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property OrderId() As String
            Get
                Return Me.orderIdField
            End Get
            Set
                Me.orderIdField = value
                Me.RaisePropertyChanged("OrderId")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property CancelReason() As String
            Get
                Return Me.cancelReasonField
            End Get
            Set
                Me.cancelReasonField = value
                Me.RaisePropertyChanged("CancelReason")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property CancelDescription() As String
            Get
                Return Me.cancelDescriptionField
            End Get
            Set
                Me.cancelDescriptionField = value
                Me.RaisePropertyChanged("CancelDescription")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class OrderResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private get_orderResultField As SendOrderResponseComplex
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property get_orderResult() As SendOrderResponseComplex
            Get
                Return Me.get_orderResultField
            End Get
            Set
                Me.get_orderResultField = value
                Me.RaisePropertyChanged("get_orderResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class GetOrder
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private orderIdField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property OrderId() As String
            Get
                Return Me.orderIdField
            End Get
            Set
                Me.orderIdField = value
                Me.RaisePropertyChanged("OrderId")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class TokenHeader
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private tokenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
                Me.RaisePropertyChanged("Token")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class send_orderResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private send_orderResultField As SendOrderResponseComplex
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property send_orderResult() As SendOrderResponseComplex
            Get
                Return Me.send_orderResultField
            End Get
            Set
                Me.send_orderResultField = value
                Me.RaisePropertyChanged("send_orderResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class PractitionerComplexModel
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private nameField As String
        
        Private firstSurnameField As String
        
        Private lastSurnameField As String
        
        Private emailField As String
        
        Private phoneCodeField As String
        
        Private phoneNumberField As String
        
        Private genderField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property FirstSurname() As String
            Get
                Return Me.firstSurnameField
            End Get
            Set
                Me.firstSurnameField = value
                Me.RaisePropertyChanged("FirstSurname")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property LastSurname() As String
            Get
                Return Me.lastSurnameField
            End Get
            Set
                Me.lastSurnameField = value
                Me.RaisePropertyChanged("LastSurname")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
                Me.RaisePropertyChanged("Email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property PhoneCode() As String
            Get
                Return Me.phoneCodeField
            End Get
            Set
                Me.phoneCodeField = value
                Me.RaisePropertyChanged("PhoneCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property PhoneNumber() As String
            Get
                Return Me.phoneNumberField
            End Get
            Set
                Me.phoneNumberField = value
                Me.RaisePropertyChanged("PhoneNumber")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property Gender() As String
            Get
                Return Me.genderField
            End Get
            Set
                Me.genderField = value
                Me.RaisePropertyChanged("Gender")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class PatientComplexModel
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private identifierField As String
        
        Private nameField As String
        
        Private firstSurnameField As String
        
        Private lastSurnameField As String
        
        Private emailField As String
        
        Private genderField As String
        
        Private birthDateField As Date
        
        Private phoneCodeField As String
        
        Private phoneNumberField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property Identifier() As String
            Get
                Return Me.identifierField
            End Get
            Set
                Me.identifierField = value
                Me.RaisePropertyChanged("Identifier")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Name() As String
            Get
                Return Me.nameField
            End Get
            Set
                Me.nameField = value
                Me.RaisePropertyChanged("Name")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=2)>  _
        Public Property FirstSurname() As String
            Get
                Return Me.firstSurnameField
            End Get
            Set
                Me.firstSurnameField = value
                Me.RaisePropertyChanged("FirstSurname")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=3)>  _
        Public Property LastSurname() As String
            Get
                Return Me.lastSurnameField
            End Get
            Set
                Me.lastSurnameField = value
                Me.RaisePropertyChanged("LastSurname")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
                Me.RaisePropertyChanged("Email")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property Gender() As String
            Get
                Return Me.genderField
            End Get
            Set
                Me.genderField = value
                Me.RaisePropertyChanged("Gender")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=6)>  _
        Public Property BirthDate() As Date
            Get
                Return Me.birthDateField
            End Get
            Set
                Me.birthDateField = value
                Me.RaisePropertyChanged("BirthDate")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=7)>  _
        Public Property PhoneCode() As String
            Get
                Return Me.phoneCodeField
            End Get
            Set
                Me.phoneCodeField = value
                Me.RaisePropertyChanged("PhoneCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=8)>  _
        Public Property PhoneNumber() As String
            Get
                Return Me.phoneNumberField
            End Get
            Set
                Me.phoneNumberField = value
                Me.RaisePropertyChanged("PhoneNumber")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class FacilityComplexModel
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private identifierField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Identifier() As String
            Get
                Return Me.identifierField
            End Get
            Set
                Me.identifierField = value
                Me.RaisePropertyChanged("Identifier")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class OrderComplexModel
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private folioField As String
        
        Private descriptionField As String
        
        Private studyCodeField As String
        
        Private studyNameField As String
        
        Private modalityField As String
        
        Private roomIdentifierField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Folio() As String
            Get
                Return Me.folioField
            End Get
            Set
                Me.folioField = value
                Me.RaisePropertyChanged("Folio")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                Me.descriptionField = value
                Me.RaisePropertyChanged("Description")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property StudyCode() As String
            Get
                Return Me.studyCodeField
            End Get
            Set
                Me.studyCodeField = value
                Me.RaisePropertyChanged("StudyCode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property StudyName() As String
            Get
                Return Me.studyNameField
            End Get
            Set
                Me.studyNameField = value
                Me.RaisePropertyChanged("StudyName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Modality() As String
            Get
                Return Me.modalityField
            End Get
            Set
                Me.modalityField = value
                Me.RaisePropertyChanged("Modality")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=5)>  _
        Public Property RoomIdentifier() As String
            Get
                Return Me.roomIdentifierField
            End Get
            Set
                Me.roomIdentifierField = value
                Me.RaisePropertyChanged("RoomIdentifier")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class SendOrderRequest
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private orderField As OrderComplexModel
        
        Private facilityField As FacilityComplexModel
        
        Private patientField As PatientComplexModel
        
        Private physicianField As PractitionerComplexModel
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property Order() As OrderComplexModel
            Get
                Return Me.orderField
            End Get
            Set
                Me.orderField = value
                Me.RaisePropertyChanged("Order")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Facility() As FacilityComplexModel
            Get
                Return Me.facilityField
            End Get
            Set
                Me.facilityField = value
                Me.RaisePropertyChanged("Facility")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property Patient() As PatientComplexModel
            Get
                Return Me.patientField
            End Get
            Set
                Me.patientField = value
                Me.RaisePropertyChanged("Patient")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Physician() As PractitionerComplexModel
            Get
                Return Me.physicianField
            End Get
            Set
                Me.physicianField = value
                Me.RaisePropertyChanged("Physician")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class SendOrder
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private orderRequestField As SendOrderRequest
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property OrderRequest() As SendOrderRequest
            Get
                Return Me.orderRequestField
            End Get
            Set
                Me.orderRequestField = value
                Me.RaisePropertyChanged("OrderRequest")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class AuthenticationTokenResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private tokenField As String
        
        Private expiresField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
                Me.RaisePropertyChanged("token")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property expires() As Date
            Get
                Return Me.expiresField
            End Get
            Set
                Me.expiresField = value
                Me.RaisePropertyChanged("expires")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class authenticateResponse
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private authenticateResultField As AuthenticationTokenResponse
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true, Order:=0)>  _
        Public Property authenticateResult() As AuthenticationTokenResponse
            Get
                Return Me.authenticateResultField
            End Get
            Set
                Me.authenticateResultField = value
                Me.RaisePropertyChanged("authenticateResult")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
    Partial Public Class authenticate
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class authenticate1
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
        Public RequestHeader As EVASoap.RequestHeader
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public authenticate As EVASoap.authenticate
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RequestHeader As EVASoap.RequestHeader, ByVal authenticate As EVASoap.authenticate)
            MyBase.New
            Me.RequestHeader = RequestHeader
            Me.authenticate = authenticate
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class authenticateResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public authenticateResponse As EVASoap.authenticateResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal authenticateResponse As EVASoap.authenticateResponse)
            MyBase.New
            Me.authenticateResponse = authenticateResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SendOrder1
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
        Public TokenHeader As EVASoap.TokenHeader
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public SendOrder As EVASoap.SendOrder
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TokenHeader As EVASoap.TokenHeader, ByVal SendOrder As EVASoap.SendOrder)
            MyBase.New
            Me.TokenHeader = TokenHeader
            Me.SendOrder = SendOrder
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class send_orderResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public send_orderResponse As EVASoap.send_orderResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal send_orderResponse As EVASoap.send_orderResponse)
            MyBase.New
            Me.send_orderResponse = send_orderResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetOrder1
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
        Public TokenHeader As EVASoap.TokenHeader
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public GetOrder As EVASoap.GetOrder
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TokenHeader As EVASoap.TokenHeader, ByVal GetOrder As EVASoap.GetOrder)
            MyBase.New
            Me.TokenHeader = TokenHeader
            Me.GetOrder = GetOrder
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class OrderResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public OrderResponse As EVASoap.OrderResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal OrderResponse As EVASoap.OrderResponse)
            MyBase.New
            Me.OrderResponse = OrderResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelOrder1
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
        Public TokenHeader As EVASoap.TokenHeader
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public CancelOrder As EVASoap.CancelOrder
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TokenHeader As EVASoap.TokenHeader, ByVal CancelOrder As EVASoap.CancelOrder)
            MyBase.New
            Me.TokenHeader = TokenHeader
            Me.CancelOrder = CancelOrder
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelOrderResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public CancelOrderResponse As EVASoap.CancelOrderResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CancelOrderResponse As EVASoap.CancelOrderResponse)
            MyBase.New
            Me.CancelOrderResponse = CancelOrderResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ScheduleOrder1
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
        Public TokenHeader As EVASoap.TokenHeader
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public ScheduleOrder As EVASoap.ScheduleOrder
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TokenHeader As EVASoap.TokenHeader, ByVal ScheduleOrder As EVASoap.ScheduleOrder)
            MyBase.New
            Me.TokenHeader = TokenHeader
            Me.ScheduleOrder = ScheduleOrder
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class schedule_orderResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public schedule_orderResponse As EVASoap.schedule_orderResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal schedule_orderResponse As EVASoap.schedule_orderResponse)
            MyBase.New
            Me.schedule_orderResponse = schedule_orderResponse
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelAppointment1
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/")>  _
        Public TokenHeader As EVASoap.TokenHeader
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public CancelAppointment As EVASoap.CancelAppointment
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TokenHeader As EVASoap.TokenHeader, ByVal CancelAppointment As EVASoap.CancelAppointment)
            MyBase.New
            Me.TokenHeader = TokenHeader
            Me.CancelAppointment = CancelAppointment
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class cancel_appointmentResponse1
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://schemas.xmlsoap.org/soap/envelope/", Order:=0)>  _
        Public cancel_appointmentResponse As EVASoap.cancel_appointmentResponse
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal cancel_appointmentResponse As EVASoap.cancel_appointmentResponse)
            MyBase.New
            Me.cancel_appointmentResponse = cancel_appointmentResponse
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface pacs_soap_serviceChannel
        Inherits EVASoap.pacs_soap_service, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class pacs_soap_serviceClient
        Inherits System.ServiceModel.ClientBase(Of EVASoap.pacs_soap_service)
        Implements EVASoap.pacs_soap_service
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_authenticate(ByVal request As EVASoap.authenticate1) As EVASoap.authenticateResponse1 Implements EVASoap.pacs_soap_service.authenticate
            Return MyBase.Channel.authenticate(request)
        End Function
        
        Public Function authenticate(ByVal RequestHeader As EVASoap.RequestHeader, ByVal authenticate1 As EVASoap.authenticate) As EVASoap.authenticateResponse
            Dim inValue As EVASoap.authenticate1 = New EVASoap.authenticate1()
            inValue.RequestHeader = RequestHeader
            inValue.authenticate = authenticate1
            Dim retVal As EVASoap.authenticateResponse1 = CType(Me,EVASoap.pacs_soap_service).authenticate(inValue)
            Return retVal.authenticateResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_authenticateAsync(ByVal request As EVASoap.authenticate1) As System.Threading.Tasks.Task(Of EVASoap.authenticateResponse1) Implements EVASoap.pacs_soap_service.authenticateAsync
            Return MyBase.Channel.authenticateAsync(request)
        End Function
        
        Public Function authenticateAsync(ByVal RequestHeader As EVASoap.RequestHeader, ByVal authenticate As EVASoap.authenticate) As System.Threading.Tasks.Task(Of EVASoap.authenticateResponse1)
            Dim inValue As EVASoap.authenticate1 = New EVASoap.authenticate1()
            inValue.RequestHeader = RequestHeader
            inValue.authenticate = authenticate
            Return CType(Me,EVASoap.pacs_soap_service).authenticateAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_SendOrder(ByVal request As EVASoap.SendOrder1) As EVASoap.send_orderResponse1 Implements EVASoap.pacs_soap_service.SendOrder
            Return MyBase.Channel.SendOrder(request)
        End Function
        
        Public Function SendOrder(ByVal TokenHeader As EVASoap.TokenHeader, ByVal SendOrder1 As EVASoap.SendOrder) As EVASoap.send_orderResponse
            Dim inValue As EVASoap.SendOrder1 = New EVASoap.SendOrder1()
            inValue.TokenHeader = TokenHeader
            inValue.SendOrder = SendOrder1
            Dim retVal As EVASoap.send_orderResponse1 = CType(Me,EVASoap.pacs_soap_service).SendOrder(inValue)
            Return retVal.send_orderResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_SendOrderAsync(ByVal request As EVASoap.SendOrder1) As System.Threading.Tasks.Task(Of EVASoap.send_orderResponse1) Implements EVASoap.pacs_soap_service.SendOrderAsync
            Return MyBase.Channel.SendOrderAsync(request)
        End Function
        
        Public Function SendOrderAsync(ByVal TokenHeader As EVASoap.TokenHeader, ByVal SendOrder As EVASoap.SendOrder) As System.Threading.Tasks.Task(Of EVASoap.send_orderResponse1)
            Dim inValue As EVASoap.SendOrder1 = New EVASoap.SendOrder1()
            inValue.TokenHeader = TokenHeader
            inValue.SendOrder = SendOrder
            Return CType(Me,EVASoap.pacs_soap_service).SendOrderAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_GetOrder(ByVal request As EVASoap.GetOrder1) As EVASoap.OrderResponse1 Implements EVASoap.pacs_soap_service.GetOrder
            Return MyBase.Channel.GetOrder(request)
        End Function
        
        Public Function GetOrder(ByVal TokenHeader As EVASoap.TokenHeader, ByVal GetOrder1 As EVASoap.GetOrder) As EVASoap.OrderResponse
            Dim inValue As EVASoap.GetOrder1 = New EVASoap.GetOrder1()
            inValue.TokenHeader = TokenHeader
            inValue.GetOrder = GetOrder1
            Dim retVal As EVASoap.OrderResponse1 = CType(Me,EVASoap.pacs_soap_service).GetOrder(inValue)
            Return retVal.OrderResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_GetOrderAsync(ByVal request As EVASoap.GetOrder1) As System.Threading.Tasks.Task(Of EVASoap.OrderResponse1) Implements EVASoap.pacs_soap_service.GetOrderAsync
            Return MyBase.Channel.GetOrderAsync(request)
        End Function
        
        Public Function GetOrderAsync(ByVal TokenHeader As EVASoap.TokenHeader, ByVal GetOrder As EVASoap.GetOrder) As System.Threading.Tasks.Task(Of EVASoap.OrderResponse1)
            Dim inValue As EVASoap.GetOrder1 = New EVASoap.GetOrder1()
            inValue.TokenHeader = TokenHeader
            inValue.GetOrder = GetOrder
            Return CType(Me,EVASoap.pacs_soap_service).GetOrderAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_CancelOrder(ByVal request As EVASoap.CancelOrder1) As EVASoap.CancelOrderResponse1 Implements EVASoap.pacs_soap_service.CancelOrder
            Return MyBase.Channel.CancelOrder(request)
        End Function
        
        Public Function CancelOrder(ByVal TokenHeader As EVASoap.TokenHeader, ByVal CancelOrder1 As EVASoap.CancelOrder) As EVASoap.CancelOrderResponse
            Dim inValue As EVASoap.CancelOrder1 = New EVASoap.CancelOrder1()
            inValue.TokenHeader = TokenHeader
            inValue.CancelOrder = CancelOrder1
            Dim retVal As EVASoap.CancelOrderResponse1 = CType(Me,EVASoap.pacs_soap_service).CancelOrder(inValue)
            Return retVal.CancelOrderResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_CancelOrderAsync(ByVal request As EVASoap.CancelOrder1) As System.Threading.Tasks.Task(Of EVASoap.CancelOrderResponse1) Implements EVASoap.pacs_soap_service.CancelOrderAsync
            Return MyBase.Channel.CancelOrderAsync(request)
        End Function
        
        Public Function CancelOrderAsync(ByVal TokenHeader As EVASoap.TokenHeader, ByVal CancelOrder As EVASoap.CancelOrder) As System.Threading.Tasks.Task(Of EVASoap.CancelOrderResponse1)
            Dim inValue As EVASoap.CancelOrder1 = New EVASoap.CancelOrder1()
            inValue.TokenHeader = TokenHeader
            inValue.CancelOrder = CancelOrder
            Return CType(Me,EVASoap.pacs_soap_service).CancelOrderAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_ScheduleOrder(ByVal request As EVASoap.ScheduleOrder1) As EVASoap.schedule_orderResponse1 Implements EVASoap.pacs_soap_service.ScheduleOrder
            Return MyBase.Channel.ScheduleOrder(request)
        End Function
        
        Public Function ScheduleOrder(ByVal TokenHeader As EVASoap.TokenHeader, ByVal ScheduleOrder1 As EVASoap.ScheduleOrder) As EVASoap.schedule_orderResponse
            Dim inValue As EVASoap.ScheduleOrder1 = New EVASoap.ScheduleOrder1()
            inValue.TokenHeader = TokenHeader
            inValue.ScheduleOrder = ScheduleOrder1
            Dim retVal As EVASoap.schedule_orderResponse1 = CType(Me,EVASoap.pacs_soap_service).ScheduleOrder(inValue)
            Return retVal.schedule_orderResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_ScheduleOrderAsync(ByVal request As EVASoap.ScheduleOrder1) As System.Threading.Tasks.Task(Of EVASoap.schedule_orderResponse1) Implements EVASoap.pacs_soap_service.ScheduleOrderAsync
            Return MyBase.Channel.ScheduleOrderAsync(request)
        End Function
        
        Public Function ScheduleOrderAsync(ByVal TokenHeader As EVASoap.TokenHeader, ByVal ScheduleOrder As EVASoap.ScheduleOrder) As System.Threading.Tasks.Task(Of EVASoap.schedule_orderResponse1)
            Dim inValue As EVASoap.ScheduleOrder1 = New EVASoap.ScheduleOrder1()
            inValue.TokenHeader = TokenHeader
            inValue.ScheduleOrder = ScheduleOrder
            Return CType(Me,EVASoap.pacs_soap_service).ScheduleOrderAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_CancelAppointment(ByVal request As EVASoap.CancelAppointment1) As EVASoap.cancel_appointmentResponse1 Implements EVASoap.pacs_soap_service.CancelAppointment
            Return MyBase.Channel.CancelAppointment(request)
        End Function
        
        Public Function CancelAppointment(ByVal TokenHeader As EVASoap.TokenHeader, ByVal CancelAppointment1 As EVASoap.CancelAppointment) As EVASoap.cancel_appointmentResponse
            Dim inValue As EVASoap.CancelAppointment1 = New EVASoap.CancelAppointment1()
            inValue.TokenHeader = TokenHeader
            inValue.CancelAppointment = CancelAppointment1
            Dim retVal As EVASoap.cancel_appointmentResponse1 = CType(Me,EVASoap.pacs_soap_service).CancelAppointment(inValue)
            Return retVal.cancel_appointmentResponse
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function EVASoap_pacs_soap_service_CancelAppointmentAsync(ByVal request As EVASoap.CancelAppointment1) As System.Threading.Tasks.Task(Of EVASoap.cancel_appointmentResponse1) Implements EVASoap.pacs_soap_service.CancelAppointmentAsync
            Return MyBase.Channel.CancelAppointmentAsync(request)
        End Function
        
        Public Function CancelAppointmentAsync(ByVal TokenHeader As EVASoap.TokenHeader, ByVal CancelAppointment As EVASoap.CancelAppointment) As System.Threading.Tasks.Task(Of EVASoap.cancel_appointmentResponse1)
            Dim inValue As EVASoap.CancelAppointment1 = New EVASoap.CancelAppointment1()
            inValue.TokenHeader = TokenHeader
            inValue.CancelAppointment = CancelAppointment
            Return CType(Me,EVASoap.pacs_soap_service).CancelAppointmentAsync(inValue)
        End Function
    End Class
End Namespace
